---
- name: restart transmission
  systemd:
        name: transmission-daemon
        state: restarted
        daemon_reload: yes

- name: restart lighttpd
  systemd:
        name: lighttpd
        state: restarted
        daemon_reload: yes
...
