---
- name: "port {{ torrent_port }} is open"
  firewalld:
    zone: public
    port: "{{ torrent_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  when: firewall_protection is defined

- name: "{{ torrent_package }} is installed"
  package:
    name: "{{ torrent_package }}"
    state: present

- name: "{{ torrent_configuration }} is up-to-date"
  copy:
    src: settings.json
    dest: "{{ torrent_configuration }}"
  notify: reload torrent configuration

- meta: flush_handlers

- name: "{{ torrent_service }} is started and enabled"
  systemd:
    name: "{{ torrent_service }}"
    state: started
    enabled: yes
