---
- name: transmission is installed
  dnf:
        name: transmission-daemon
        state: latest

- name: transmission is configured
  copy:
        src: settings.json
        dest: /var/lib/transmission/.config/transmission-daemon/
  notify:
        - restart transmission

- meta: flush_handlers

- name: transmission is started and enabled
  systemd:
        name: transmission-daemon
        state: started
        enabled: yes
...
