---
- name: "external USB drive {{ share_device }} is mounted on {{ share_mount_point }}"
  mount:
    name: "{{ share_mount_point }}"
    src: "{{ share_device }}"
    fstype: ntfs-3g
    state: mounted

- name: "{{ share_package }} is installed"
  package:
    name: "{{ share_package }}"
    state: present

- name: "{{ share_configuration }} is up-to-date"
  copy:
    src: smb.conf
    dest: "{{ share_configuration }}"
  notify: reload share configuration

- meta: flush_handlers

- name: "{{ share_service }} is started and enabled"
  systemd:
    name: "{{ share_service }}"
    state: started
    enabled: yes
