---
- name: tools are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ tools_packages }}"

- name: fish is the default shell
  user:
    name: "{{ user }}"
    state: present
    shell: /usr/bin/fish

- name: vim is configured
  copy:
    src: vimrc
    dest: "/home/{{ user }}/.vimrc"
    owner: "{{ user }}"
...
