---
- name: tools are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ tools_packages }}"

- name: powerlevel9k is installed
  synchronize:
    src: powerlevel9k
    dest: /home/tvuillemin/
  become: no
  # The synchronize module has some compatibility problems with the become module

- name: zsh is configured
  copy:
    src: zshrc
    dest: /home/tvuillemin/.zshrc
    owner: tvuillemin

- name: zsh is the default shell
  user:
    name: tvuillemin
    state: present
    shell: /usr/bin/zsh

- name: vim is configured
  copy:
    src: vimrc
    dest: /home/tvuillemin/.vimrc
    owner: tvuillemin
...
