---
- name: EPEL repository is enabled
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: RPM Fusion free repository is enabled
  yum:
    name: https://download1.rpmfusion.org/free/el/updates/6/i386/rpmfusion-free-release-6-1.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: RPM Fusion non-free repository is enabled
  yum:
    name: https://download1.rpmfusion.org/nonfree/el/updates/6/i386/rpmfusion-nonfree-release-6-1.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: installed packages are up-to-date
  package:
    name: '*'
    state: latest
...
