---
- hosts: all
  roles:
    - shell

- hosts: raspberrypi
  roles:
    - share
    - torrent
    - webserver
  vars:
    torrent_reverse_proxy: true

- hosts: gameserver
  roles:
    - starbound
...
