---
- hosts: all
  roles:
    - role: shell
      tags: ['shell', 'linux']

- hosts: raspberrypi
  roles:
    - role: transmission
      tags: ['transmission', 'torrent']
    - role: lighttpd
      tags: ['lighttpd', 'reverse_proxy']

# - name: GAMING
#   hosts: gameserver
#   roles:
#     - role: nagios
#       tags: ['nagios', 'monitoring']
#     - role: git
#       tags: ['git']
#     - role: transmission
#       tags: ['transmission', 'torrent']
#     - role: minecraft
#       tags: ['minecraft', 'games']
#     - role: mumble
#       tags: ['mumble', 'murmur', 'games']
      # - role: dontstarve
      #   tags: ['dontstarve', 'games']
      # - role: starbound
      #   tags: ['starbound', 'games']
...
