---
- hosts: all
  roles:
    - role: shell
      tags: ['shell', 'linux']

- hosts: raspberrypi
  roles:
    - role: transmission
      tags: ['transmission', 'torrent']
    - role: lighttpd
      tags: ['lighttpd', 'reverse_proxy']
...
