---
- name: BASICS
  hosts: all
  roles:
        - role: fedora
          tags: ['fedora']

- name: GAMING
  hosts: gameserver
  roles:
        - role: minecraft
          tags: ['minecraft']
        - role: starbound
          tags: ['starbound']

- name: MEDIA
  hosts: mediaserver
  roles:
        - dlna
        - smb
        - torrent
...
