---
- name: BASICS
  hosts: all
  roles:
    - fedora

- name: GAMING
  hosts: gameserver
  roles:
    - { role: minecraft, tags: [ 'minecraft' ] }
    - starbound

- name: MEDIA
  hosts: mediaserver
  roles:
    - dlna
    - smb
    - torrent
