---
- name: GAMING
  hosts: gameserver
  roles:
        - role: dontstarve
          tags: ['dontstarve']
        - role: minecraft
          tags: ['minecraft']
        - role: starbound
          tags: ['starbound']
        - role: mumble
          tags: ['mumble', 'murmur']
...
