---
- name: GAMING
  hosts: gameserver
  roles:
        - role: minecraft
          tags: ['minecraft']
        - role: starbound
          tags: ['starbound']

# - name: MEDIA
#   hosts: mediaserver
#   roles:
#         - dlna
#         - smb
#         - torrent
...
