---

- name: installed packages are up-to-date
  dnf: name=* state=latest

# - name: rpmfusion free repository is enabled
#   dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm state=present disable_gpg_check=yes

# - name: rpmfusion nonfree repository is enabled
#   dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm disable_gpg_check=yes

- name: ansible utility packages are installed
  dnf: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - python-firewall

- name: zsh is installed
  dnf: name=zsh state=latest

- name: zsh is configured
  copy: src=zshrc dest=/home/tvuillemin/.zshrc owner=tvuillemin

- name: zsh is the default shell
  user: name=tvuillemin state=present shell=/usr/bin/zsh

- name: vim is installed
  dnf: name=vim state=latest

- name: vim is configured
  copy: src=vimrc dest=/home/tvuillemin/.vimrc owner=tvuillemin

- name: htop is installed
  dnf: name=htop state=latest

- name: firewall is started
  systemd: name=firewalld state=started enabled=yes
