# Inspired by https://github.com/groks/ansible-repo-extra
---
- name: is the rpmfusion-free repo installed
  command: dnf info rpmfusion-free-release
  register: rpmfusion_free_installed
  ignore_errors: True

- name: is the rpmfusion-nonfree repo installed
  command: dnf info rpmfusion-nonfree-release
  register: rpmfusion_nonfree_installed
  ignore_errors: True

- name: install rpmfusion-free repo
  dnf:
        name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
        state: present
  when: rpmfusion_free_installed|failed

- name: install rpmfusion-nonfree repo
  dnf:
        name: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
        state: present
  when: rpmfusion_nonfree_installed|failed
...
