---
-   name: java is installed
    yum:
        name: java-1.8.0-openjdk
        state: latest

-   name: port is open
    firewalld:
        zone: public
        port: 25565/tcp
        state: enabled
        permanent: true
        immediate: true

-   name: dedicated user exists
    user:
        name: minecraft
        group: daemon
        shell: /usr/bin/bash

-   name: directory exists
    file:
        path: /opt/minecraft
        state: directory
        owner: minecraft
        group: daemon

-   name: server is downloaded
    get_url:
        url: https://launcher.mojang.com/mc/game/1.11.2/server/f00c294a1576e03fddcac777c3cf4c7d404c4ba4/server.jar
        dest: /opt/minecraft/minecraft_server.jar
        checksum: sha1:f00c294a1576e03fddcac777c3cf4c7d404c4ba4
        owner: minecraft
        group: daemon
    register: download_task
    notify:
        - restart minecraft

-   name: transfer the world manually
    pause:
        prompt: Upload the minecraft world now if necessary. Then hit Ctrl-C.
    when: download_task|changed

-   include: server_properties.yml

-   name: white list is downloaded
    copy:
        src: whitelist.json
        dest: /opt/minecraft/whitelist.json
        owner: minecraft
        group: daemon
    notify:
        - restart minecraft

-   name: OP list is downloaded
    copy:
        src: ops.json
        dest: /opt/minecraft/ops.json
        owner: minecraft
        group: daemon
    notify:
        - restart minecraft

-   name: eula is set to true
    copy:
        src: eula.txt
        dest: /opt/minecraft/eula.txt
        owner: minecraft
        group: daemon
    notify:
        - restart minecraft

-   name: start script is installed
    template:
        src: start_minecraft.sh.j2
        dest: /opt/minecraft/start_minecraft.sh
        owner: minecraft
        group: daemon
    notify:
        - restart minecraft

-   name: start script is executable
    file:
        path: /opt/minecraft/start_minecraft.sh
        mode: "u+x"
        owner: minecraft
        group: daemon

-   include: snapshot.yml

-   name: service is installed
    copy:
        src: minecraft.service
        dest: /etc/systemd/system/minecraft.service
    notify:
        - restart minecraft

-   meta: flush_handlers

-   name: service is started
    systemd:
        name: minecraft
        state: started
        enabled: yes
...
