---
- name: steam dependencies are installed
  package:
        name: '{{ item }}'
        state: present
  with_items:
        - libgcc.x86_64
        - libgcc.i686
        - glibc.i686

- name: steamcmd directory exists
  file:
        path: /opt/steamcmd
        state: directory

- name: steamcmd archive is downloaded
  get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /opt/steamcmd.tgz
  register: archive

- name: steamcmd archive is extracted
  unarchive:
        src: /opt/steamcmd.tgz
        dest: /opt/steamcmd
        remote_src: yes
  when: archive|changed
...
