---
- name: steam package is installed
  dnf: name=steam state=latest

- name: steamcmd directory exists
  file: path=/opt/steamcmd state=directory

- name: steamcmd archive is extracted
  unarchive: src=https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz dest=/opt/steamcmd remote_src=yes
