---
- name: firewall daemon is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firewalld
    - python-firewall

- name: firewall is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: tools are installed
  package:
    name: libselinux-python
    state: present
...
