---
- name: firewall daemon is installed
  package:
    name: firewalld
    state: present

- name: firewall is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: firewall default zone is attached to the main network interface
  command: firewall-cmd --permanent --zone=public --change-interface=eth0
  changed_when: false
...
