# Terminal parameters
export PATH="/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export TERM="xterm-256color"
export EDITOR='vim'
export LANG=en_GB.UTF-8
autoload -U compinit
compinit

# Zsh general parameters
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
ENABLE_CORRECTION="false"
HYPHEN_INSENSITIVE="true"

# Zsh history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
HIST_STAMPS="yyyy-mm-dd"
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Aliases
alias ls="ls --color"
alias ll="ls -l"
alias gco="git checkout"
alias ggui="gitg --all"
alias gst="git status"
alias psg="ps aux | grep -v grep | grep"
alias sudo="sudo -E"
alias svi="sudo vim"

# Powerline Theme
POWERLEVEL9K_MODE="nerdfont-fontconfig"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=7
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context root_indicator ip dir vcs virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(load ram disk_usage time)
POWERLEVEL9K_TIME_FORMAT="%D{%Y-%m-%d \uf073  %H:%M}"
POWERLEVEL9K_VCS_GIT_ICON=$'\uF296 '
POWERLEVEL9K_VCS_BRANCH_ICON=$'\uF126 '
POWERLEVEL9K_PYTHON_ICON=$'\U1F40D'
POWERLEVEL9K_DISK_ICON=$'\uF0A0'
source $HOME/powerlevel9k/powerlevel9k.zsh-theme
