# Terminal parameters
export PATH="/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export TERM="xterm-256color"
export EDITOR='vim'
export LANG=en_GB.UTF-8
autoload -U compinit
compinit

# Zsh general parameters
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
ENABLE_CORRECTION="false"
HYPHEN_INSENSITIVE="true"

# Zsh history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
HIST_STAMPS="yyyy-mm-dd"
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Aliases
alias ls="ls --color"
alias ll="ls -l"
alias gco="git checkout"
alias ggui="gitg --all"
alias gst="git status"
alias psg="ps aux | grep -v grep | grep"
alias sudo="sudo -E"
alias svi="sudo vim"

# Powerline Theme
POWERLEVEL9K_MODE="awesome-fontconfig"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_CUSTOM_PROXY_STATUS="prompt_proxy"
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=7
POWERLEVEL9K_TIME_FORMAT="%D{%Y-%m-%d \uf073 %H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
source  $HOME/powerlevel9k/powerlevel9k.zsh-theme
