---
# - name: port is open
#   firewalld:
#         zone: public
#         port: 21025/tcp
#         state: enabled
#         permanent: true
#         immediate: true

- name: dependencies are installed
  package:
        name: '{{ item }}'
        state: present
  with_items:
        - libcurl.i686

# http://forums.kleientertainment.com/topic/50011-centos-redhat-libcurl-gnutls-workaround/
- name: libcurl workaround for centos is done
  file:
        src: /usr/lib/libcurl.so.4
        dest: /usr/lib/libcurl-gnutls.so.4
        state: link

- name: dedicated user exists
  user:
        name: dontstarve
        group: daemon
        shell: /usr/bin/bash

- name: server is up to date
  command: /opt/steamcmd/steamcmd.sh +login {{ steam_login }} '{{ steam_password }}' +force_install_dir /opt/dontstarve +app_update 343050 validate +quit
  notify:
        - restart dont starve

- name: server directory belongs to the dedicated user
  file:
        path: /opt/dontstarve
        owner: dontstarve
        group: daemon
        mode: "u=rwx,g=rx,o=rx"
        recurse: yes

- name: service is installed
  copy:
        src: dontstarve.service
        dest: /etc/systemd/system/dontstarve.service
  notify:
        - restart dont starve

- meta: flush_handlers

- name: service is started
  systemd:
        name: dontstarve
        state: started
        enabled: yes
...
