---
- name: port is open
  firewalld:
    zone: public
    port: 9091/tcp
    state: enabled
    permanent: true
    immediate: true
  when: firewall_protection is defined

- name: software is installed
  package:
    name: transmission-daemon
    state: present

- name: configuration file is up-to-date
  copy:
    src: settings.json
    dest: /etc/transmission-daemon/
  register: configuration

- name: service is reloaded
  systemd:
    name: transmission-daemon
    state: reloaded
  when: configuration | changed

- name: service is started and enabled
  systemd:
    name: transmission-daemon
    state: started
    enabled: yes
...
