---
- name: port is open
  firewalld:
    zone: public
    port: 9091/tcp
    state: enabled
    permanent: true
    immediate: true
  when: firewall_protection is defined

- name: software is installed
  package:
    name: transmission-daemon
    state: present

- name: check if the configuration needs to be updated
  copy:
    src: settings.json
    dest: /etc/transmission-daemon/
  register: configuration_check
  # Transmission configuration cannot be updated if the daemon is running

- name: service is stopped
  systemd:
    name: transmission-daemon
    state: stopped
  when: configuration_check|changed

- name: software is configured
  copy:
    src: settings.json
    dest: /etc/transmission-daemon//transmission-daemon/
  when: configuration_check|changed

- name: service is started and enabled
  systemd:
    name: transmission-daemon
    state: started
    enabled: yes
...
