---
- name: dependencies are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - bzip2
    - mariadb

- name: TCP port is open
  firewalld:
    zone: public
    port: 64738/tcp
    state: enabled
    permanent: true
    immediate: true

- name: UDP port is open
  firewalld:
    zone: public
    port: 64738/udp
    state: enabled
    permanent: true
    immediate: true

- name: dedicated user exists
  user:
    name: mumble
    group: daemon
    shell: /usr/bin/bash

- name: server directory exists
  file:
    path: /opt/mumble
    state: directory
    owner: mumble
    group: daemon

- name: server archive is downloaded
  get_url:
    url: "{{ mumble_server_url }}"
    dest: /opt/mumble.tar.bz2
  register: archive

- name: server archive is extracted
  unarchive:
    remote_src: yes
    src: /opt/mumble.tar.bz2
    dest: /opt/mumble
  when: archive|changed
  become_user: mumble

- name: service is installed
  copy:
    src: mumble.service
    dest: /etc/systemd/system/mumble.service
  notify:
    - restart mumble

- name: service is started
  systemd:
    name: mumble
    state: started
    enabled: yes
...
