---
- name: starbound server is up to date
  command: /opt/steamcmd/steamcmd.sh +login {{ steam_login }} '{{ steam_password }}' +force_install_dir /opt/starbound +app_update 211820 validate +quit

- name: starbound service is installed
  copy: src=starbound.service dest=/etc/systemd/system/starbound.service

- name: starbound service is restarted
  systemd: name=starbound state=restarted daemon_reload=yes
