---
- name: "{{ webserver_package }} is installed"
  package:
    name: "{{ webserver_package }}"
    state: present

- name: "{{ webserver_configuration }} is up-to-date"
  copy:
    src: external.conf
    dest: "{{ webserver_configuration }}"
  when: torrent_reverse_proxy
  notify: reload webserver configuration

- meta: flush_handlers

- name: "{{ webserver_service }} is started and enabled"
  systemd:
    name: "{{ webserver_service }}"
    state: started
    enabled: yes
