---
- name: Configuring the media server
  hosts: mediaserver
  roles:
    - role: base
      tags: [base]
    - role: jellyfin
      tags: [jellyfin, media]
    - role: nas-client
      tags: [nas-client]
    - role: transmission
      tags: [transmission, torrent]

